# Generated by Django 5.1.2 on 2024-11-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
