# Generated by Django 5.1.2 on 2024-11-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_loginhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Enquiry_Login',
        ),
    ]
