# Generated by Django 5.1.2 on 2024-11-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_rename_request_enquiry_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
