# Generated by Django 5.1.2 on 2025-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_enquiry_age_alter_enquiry_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
