# Generated by Django 5.1.2 on 2025-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_videoupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
