# Generated by Django 5.1.2 on 2025-01-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_videoupload_video_url_alter_videoupload_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='video_url',
            new_name='streaming_url',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='video_file',
        ),
    ]
